using System;

/* Triangle, pentagonal, and hexagonal numbers are generated by the following formulae:

Triangle	 	Tn=n(n+1)/2	 	1, 3, 6, 10, 15, ...
Pentagonal	 	Pn=n(3n−1)/2	 	1, 5, 12, 22, 35, ...
Hexagonal	 	Hn=n(2n−1)	 	1, 6, 15, 28, 45, ...
It can be verified that T(285) = P(165) = H(143) = 40755.

Find the next triangle number that is also pentagonal and hexagonal. */

namespace ProjectEuler
{
    public class Problem45
    {
        public void Solve()
        {
            int count = 0;
            int n = 142;
            while(count < 2)
            {
                n++;

                long T = n * (2 * n - 1);

                if(isTriangular(T) && isPentagonal(T))
                {
                    count++;
                    Console.WriteLine(T);
                }
            }
        }

        bool isTriangular(long n)
        {
            double num = (-1 + Math.Sqrt(1 + 8 * n)) / 2;

            return num == (int)num;
        }

        bool isPentagonal (long n)
        {
            double num = (1 + Math.Sqrt(1 + 24 * n)) / 6;

            return num == (int)num;
        }
    }
}
