using System;
using System.Collections.Generic;

/*Pentagonal numbers are generated by the formula, Pn=n(3n−1)/2. The first ten pentagonal numbers are:

1, 5, 12, 22, 35, 51, 70, 92, 117, 145, ...

It can be seen that P4 + P7 = 22 + 70 = 92 = P8. However, their difference, 70 − 22 = 48, is not pentagonal.

Find the pair of pentagonal numbers, Pj and Pk,
for which their sum and difference are pentagonal and D = |Pk − Pj| is minimised; what is the value of D? */

namespace ProjectEuler
{
    public class Problem44
    {

        public void Solve()
        {
            int D = 0;

            bool found = false;

            int n = 0;
            while (!found)
            {
                n++;
                int Pk = n * (3 * n - 1) / 2;
                for(int m = n - 1; m > 0; m--)
                {
                    int Pj = m * (3 * m - 1) / 2;
                    if(isPentagonal(Pk - Pj) && isPentagonal(Pk + Pj))
                    {
                        D = Pk - Pj;
                    }
                    if(D != 0 && Pk - Pj > D)
                    {
                        found = true;
                    }
                }
            }

            Console.Write(D);
        }

        bool isPentagonal(int n)
        {
            float f = (1 + MathF.Sqrt(1 + 24 * n)) / 6;

            if(f % 1 == 0)
            {
                return true;
            }

            return false;
        }
    }
}
